### PR TITLE
Automate Vault Setup

### LINKED ISSUE #207: Automate vault initalization and login on the admin machine (Ansible Script)
Reference init.sh file

```
sudo apt update && sudo apt install gpg
wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
sudo apt update
sudo apt install vault

# Set Vault Addr in Environment
echo "export VAULT_ADDR=http://127.0.0.1:8200" >> ~/.bashrc

# Initialized the vault
vault operator init -key-shares=6 -key-threshold=3 >> initialization-data.txt

# Unsealed the vault manually
# vault operator unseal <key>
# vault operator unseal <key>
# vault operator unseal <key>

# Logged in to vault using token
# vault login <token>

# Enable the secret engine
vault secrets enable -version=2 -path=secret kv

# Put test secret
vault kv put secret/prod/test x=y
```

Reference initialization-data.txt

```
Unseal Key 1: nckjsnckdsncnskcnsk
Unseal Key 2: cksckjdnsjcnkdsnclksdnlcnsl
Unseal Key 3: cdskcnlkdsnclkndslcnsdl
Unseal Key 4: ljdlqwmxkldsnkjcbndsknc
Unseal Key 5:  snjdsbcjbsdljcbjdsbcjlsdbc
Unseal Key 6: ccsdbjkbdjksbcibdsicbidb

Initial Root Token: hvs.cnkjdsnkdsnkcncdskcns

Vault initialized with 6 key shares and a key threshold of 3. Please securely
distribute the key shares printed above. When the Vault is re-sealed,
restarted, or stopped, you must supply at least 3 of these keys to unseal it
before it can start servicing requests.

Vault does not store the generated root key. Without at least 3 keys to
reconstruct the root key, Vault will remain permanently sealed!

It is possible to generate new unseal keys, provided you have a quorum of
existing unseal keys shares. See "vault operator rekey" for more information.
```

### PR DESCRIPTION
**Pull request by Manas23601**
Fixes #207

### CODE REVIEW

**Comment by singhalkarun** [comment]
Hey @Manas23601 can you please share screenshot of ansible logs after running the updated script?

**Comment by Manas23601** [comment]
> Hey @Manas23601 can you please share screenshot of ansible logs after running the updated script?

sure

**Comment by Manas23601** [comment]
Screenshot from 2023-07-21 12-04-16
Screenshot from 2023-07-21 12-04-43
image

Let me if you want the Detailed verbose output. I commented out the docker compose task as I already had it running

**Comment by singhalkarun** [comment]
I would prefer verbosed output. You can save logs in file and attach the file itself @Manas23601.

**Comment by Manas23601** [comment]
[ansible_logs.txt](https://github.com/Samagra-Development/ai-tools/files/12123427/ansible_logs.txt)

**Pull request closed without merging**
