### PR TITLE
Exploring DistilBERT as a Lightweight Alternative for Context-Based Question Answering in the Social Welfare Domain

### PR DESCRIPTION
**Pull request by shephinphilip**
## Choice of Model: DistilBERT
DistilBERT is a lighter and more efficient version of the BERT model. It retains most of BERT's performance while reducing its memory and computational requirements. Given the goal of finding simpler models, DistilBERT is an excellent candidate due to its balance between performance and resource efficiency.

##Implementation Steps:
Importing Libraries:
The required libraries from the transformers package are imported: pipeline, DistilBertTokenizer, and DistilBertForQuestionAnswering.

Loading Model and Tokenizer:
The distilbert-base-cased-distilled-squad model is loaded using DistilBertForQuestionAnswering.from_pretrained, and its associated tokenizer is loaded using DistilBertTokenizer.from_pretrained.

Defining Inputs:
Paragraphs, questions, and expected answers are defined. These lists contain the relevant text for each section.

Question Generation Pipeline:
A question generation pipeline is initialized using the pipeline function from the transformers library. This pipeline is created using a pre-trained question generation model (consciousAI/question-answering-roberta-base-s-v2).

Iterating Through Sections:
The script iterates through each paragraph, question, and expected answer using a loop.

Generating Detailed Questions:
A detailed question is generated based on the current paragraph using the initialized question generation pipeline. This detailed question is designed to enhance the user's question for better context.

Combining Questions:
The user's question and the generated detailed question are combined to create a more comprehensive question for answering.

Tokenization and Answer Generation:
The combined question and the current paragraph are tokenized using the DistilBERT tokenizer. The model's start and end scores are obtained using the tokenized inputs.

Determining Start and End Indices:
The start and end indices of the predicted answer span are determined based on the highest start and end scores obtained from the model.

Decoding Answer:
The answer is decoded using the tokenizer.decode method, which takes the predicted answer span's input IDs and converts them back into human-readable text.

Printing Results:
For each paragraph, the original content, user's question, expected answer, generated question, combined question, and predicted answer are printed.

## Contribution to GitHub Issue: #150 
In response to the GitHub issue, I explored and identified a simpler model for context-based question answering: DistilBERT. I provided a detailed explanation of why DistilBERT was chosen and how it was implemented to solve the given task. By utilizing DistilBERT, the implementation aims to achieve similar performance as more complex models while reducing computational resources.

The provided code snippet demonstrates the step-by-step process of loading the model, generating questions, combining them, and predicting answers. The script iterates through provided paragraphs, questions, and expected answers, generating questions and predicting answers for each paragraph-question pair. The output includes the original content, user's question, expected answer, generated question, combined question, and predicted answer for each section.

This approach aims to highlight the feasibility of using DistilBERT as a simpler alternative to more resource-intensive models like GPT-3.5, while still achieving satisfactory performance in context-based question answering tasks within the AI-tools domain of the Samagra organization's social welfare project, AmakrusAI.

### CODE REVIEW

**Comment by H4R5H1T-007** [comment]
Can you add some output along with the questions to show how well it's performing??

**Comment by shephinphilip** [comment]
Screenshot (70)

**Comment by shephinphilip** [comment]
here is the output , i created a file to find the accuracy and performance time and used SQUAD dataset 
Accuracy: 0.808279812335968
Performance time: 0.002067089080810547 seconds

**Comment by shephinphilip** [comment]
I am closing this issue

**Pull request closed without merging**
