### PR TITLE
Created API in src/embeddings to create Vector embeddings from PDF.

### PR DESCRIPTION
**Pull request by H4R5H1T-007**

### CODE REVIEW

**Comment by H4R5H1T-007** [comment]
I ran the embedding generator on one of the given pdf from #109 and [this is the output] (https://github.com/Samagra-Development/ai-tools/files/11608991/main_text_and_chunked_text_by_sharp_change_method.txt) the code is generating by using sharp change and threshold method. @GautamR-Samagra @ChakshuGautam

**Comment by GautamR-Samagra** [comment]
Hi I went through the output and I think its clear that its not chunking in the required fashion. The chunks dont seem to be of a particular topic. We'll need to explore alternative methods to carry this out.

**Comment by H4R5H1T-007** [comment]
> Hi I went through the output and I think its clear that its not chunking in the required fashion. The chunks dont seem to be of a particular topic. We'll need to explore alternative methods to carry this out.

okay I will look for different chunking method and try to implement it. Do I need to use pytest to create unit tests for this module? @GautamR-Samagra

**Comment by H4R5H1T-007** [comment]
> @H4R5H1T-007 can you please share the notebook, I would like to learn the procedure.

you can check out my code in this commit I am using that code only and I am not using Jupyter notebook I am using Pycharm. @rishav-eulb

**Comment by GautamR-Samagra** [comment]
Closing this PR. @H4R5H1T-007  to try alternative approaches on this

**Pull request closed without merging**
