### PR TITLE
Add cached header to response

### PR DESCRIPTION
**Pull request by Poonam1607**

### CODE REVIEW

**Comment by ChakshuGautam** [comment]
@Poonam1607 how are you figuring out if the method was called or the cache was called - for example for this method - https://github.com/Samagra-Development/ai-tools/blob/12a77cbe3296eaf87bdbf5ebf47e7ac97dab315e/src/embeddings/openai/remote/model.py#L29

**Comment by Poonam1607** [comment]
> 

I have added a check and If all those conditions are met, then a custom header "ai-tools-cached" to the response indicating that it was served from the cache.

**Comment by Poonam1607** [comment]
Please let me know if I want to make any changes.

**Comment by ChakshuGautam** [comment]
Hey can you write a test that can verify this?

**Comment by ChakshuGautam** [comment]
Please reach out to me about this on Discord. This is going in the wrong direction.

**Comment by Poonam1607** [comment]
> Please reach out to me about this on Discord. This is going in the wrong direction.

I already messaged you in discord way before.

**Pull request closed without merging**
