### PR TITLE
Dynamic Generation for all existing models.

### PR DESCRIPTION
**Pull request by Manas23601**
Fixes Issue #118 

- Added Other Models to config.json
- Refactored generate.sh
    - removed empty environement field in docker-compose
    - frontslash on paths in nginx
    - closing brackets in nginx

### CODE REVIEW

**Comment by Manas23601** [comment]
@singhalkarun Can you take a look at this?

**Comment by singhalkarun** [comment]
Hey @Manas23601 I would always prefer / infront of apiBasePath to avoid any sorts of ambiguity. 

Secondly, can you please check https://github.com/Samagra-Development/ai-tools/blob/restructure/api.py#L85, this was previously being used to serve all models at once. Just to ensure backward compaitibility, please ensure the base paths of all models aligns with it.

**Comment by Manas23601** [comment]
Except for `conversation_terminator/remote` I was able to match the route format for the other models. 

I hope I have made changes in the right area for individual models routing.

**Comment by singhalkarun** [comment]
Hey @Manas23601 still can find models with apiBaseWith without / as prefix (https://github.com/Manas23601/ai-tools/blob/work-restructure/config.json#L52-L70)

2. The routes updated inside the api.py inside model folders aren't correct. Checkout [this](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) to understand how reverse proxy works and update them accordingly.

**Comment by singhalkarun** [comment]
Still, the inference endpoints doesn't match, for ex. For Bhasini based language translation, the endpoint in case of single image setup is http://domain/text_translation/bhasini/remote but in your case it is ending up at /text_translation/bhasini/remote/translate. 

Please take time and understand how the routing in working in case of single image setup, sharing reference again to understand that (https://github.com/Samagra-Development/ai-tools/blob/restructure/api.py#L85) and accordingly make changes to individual api.py files and config.json if required to make the path match.

**Pull request merged**
